package main

import "fmt"

func main() {
	if DomainLevelMap["yahoo.com"] == "super good" {
		fmt.Println("good")
	}
}
var DomainLevelMap = map[string]string{
"yahoo.com":                 "super good",
"wrestlingculture.com":      "super good",
"washingtonpost.com":        "super good",
"verywellhealth.com":        "super good",
"vanguardngr.com":           "super good",
"usatoday.com":              "super good",
"tribuneonlineng.com":       "super good",
"tribune.com.ng":            "super good",
"tooxclusive.com":           "super good",
"tmz.com":                   "super good",
"thisdaylive.com":           "super good",
"thenationonlineng.net":     "super good",
"theguardian.com":           "super good",
"thecable.ng":               "super good",
"techradar.com":             "super good",
"techpoint.ng":              "super good",
"techpoint.africa":          "super good",
"techcrunch.com":            "super good",
"techcabal.com":             "super good",
"sunnewsonline.com":         "super good",
"sportskeeda.com":           "super good",
"sports.naij.com":           "super good",
"sportinglife.ng":           "super good",
"sportinglife.com":          "super good",
"soundcity.tv":              "super good",
"skysports.com":             "super good",
"saharareporters.com":       "super good",
"rt.com":                    "super good",
"reuters.com":               "super good",
"punchng.com":               "super good",
"pulse.ng":                  "super good",
"premiumtimesng.com":        "super good",
"owngoalnigeria.com":        "super good",
"nytimes.com":               "super good",
"notjustok.com":             "super good",
"newtelegraphonline.com":    "super good",
"newtelegraphng.com":        "super good",
"news.yahoo.com":            "super good",
"news.sky.com":              "super good",
"nbcnews.com":               "super good",
"nairametrics.com":          "super good",
"naij.com":                  "super good",
"msn.com":                   "super good",
"mobile.ghanasoccernet.com": "super good",
"mirror.co.uk":              "super good",
"metro.co.uk":               "super good",
"marca.com":                 "super good",
"lindaikejisblog.com":       "super good",
"lindaikejiblog.com":        "super good",
"lindaikeji.blogspot.com":   "super good",
"lifestyle.thecable.ng":     "super good",
"leadership.ng":             "super good",
"lagosmums.com":             "super good",
"kwese.espn.com":            "super good",
"kickoff.com":               "super good",
"independent.ng":            "super good",
"independent.co.uk":         "super good",
"hotnewhiphop.com":          "super good",
"hollywoodlife.com":         "super good",
"hollywood.com":             "super good",
"guardian.ng":               "super good",
"gq-magazine.co.uk":         "super good",
"goldmyne.tv":               "super good",
"goal.com":                  "super good",
"givemesport.com":           "super good",
"foxnews.com":               "super good",
"foxbusiness.com":           "super good",
"fourfourtwo.com":           "super good",
"forbesafrica.com":          "super good",
"forbes.com":                "super good",
"food.com":                  "super good",
"financialwatchngr.com":     "super good",
"finance.yahoo.com":         "super good",
"fifa.com":                  "super good",
"fcnaija.com":               "super good",
"etonline.com":              "super good",
"espn.co.uk":                "super good",
"entertainment.naij.com":    "super good",
"edition.cnn.com":           "super good",
"dailytrust.com.ng":         "super good",
"dailypost.ng":              "super good",
"dailymail.co.uk":           "super good",
"completesportsnigeria.com": "super good",
"completesports.com":        "super good",
"cnn.com":                   "super good",
"cnbc.com":                  "super good",
"channelstv.com":            "super good",
"caughtoffside.com":         "super good",
"cafonline.com":             "super good",
"buzzfeednews.com":          "super good",
"businessinsider.com":       "super good",
"businessdayonline.com":     "super good",
"bloomberg.com":             "super good",
"bleacherreport.com":        "super good",
"bellanaijaweddings.com":    "super good",
"bellanaija.com":            "super good",
"bbc.com":                   "super good",
"bbc.co.uk":                 "super good",
"allure.vanguardngr.com":    "super good",
"aljazeera.com":             "super good",
"africanfootball.com":       "super good",
"af.reuters.com":            "super good",
"90min.com":                 "super good",
}

